#!/usr/bin/env python

########################################################################
#                             _power_status.py                         #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#       G-TeCS script to check power status, part of power_deamon      #
#                     Martin Dyer, Sheffield, 2015                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

# Tiny script to print power status to stdout
# Allows function call to be killed if it locks up
# NOT for manual use - should ONLY be called by power daemon

from __future__ import absolute_import
from __future__ import print_function

from gtecs.tecs_modules import params

try:
    x = params.POWER.status(0)
    assert isinstance(x, str) or isinstance(x, unicode)
    assert len(x) == 8
except:
    x = 'xERRORxx'

print(x)
