#!/usr/bin/env python

########################################################################
#                             _power_status.py                         #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#       G-TeCS script to check power status, part of power_deamon      #
#                     Martin Dyer, Sheffield, 2015                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

# Tiny script to print power status to stdout
# Allows function call to be killed if it locks up
# NOT for manual use - should ONLY be called by power daemon

from __future__ import absolute_import
from __future__ import print_function

from gtecs.tecs_modules import params
from gtecs.controls import power_control

IP = params.POWER_IP
port = params.POWER_PORT
if params.POWER_TYPE == 'APCPower':
    power = power_control.APCPower(IP)
elif params.POWER_TYPE == 'EthPower':
    power = power_control.EthPower(IP, port)
else:
    power = power_control.FakePower(' ',' ')

try:
    x = power.status(0)
    assert isinstance(x, str) or isinstance(x, unicode)
    assert len(x) == power.count
except:
    x = 'x' * power.count

print(x)
