#!/usr/bin/env python
"""
A script to check the dome status
"""

import os
import sys
import time
import Pyro4

from gtecs import misc
from gtecs import params
from gtecs.daemons import daemon_info


INFO_TIMEOUT = 10.
PING_LIMIT = 60.

DOME_DAEMON_ADDRESS = params.DAEMONS['dome']['ADDRESS']

start_time = time.time()
while True:
    info = daemon_info('dome')
    if type(info) == dict:
        break
    if time.time() - start_time > INFO_TIMEOUT:
        print('Failed to get info dict')
        misc.send_email(message='Failed to get dome info dictionary')
        sys.exit()
    time.sleep(1)

print(info)
if info['ping'] > PING_LIMIT:
    print('Failed to ping dome daemon')
    misc.send_email(message='Dome ping failed - daemon crashed?\nKilling and restarting daemon...')
    print('dome kill')
    cmd = 'dome kill'
    os.system(cmd)
    print('Sleeping...')
    time.sleep(10)
    print('dome start')
    cmd = 'dome start'
    os.system(cmd)
    exit()

print('Dome OK')
