#!/usr/bin/env python

########################################################################
#                                dome.py                               #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#           G-TeCS script to provide control over dome_daemon          #
#                     Martin Dyer, Sheffield, 2015                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

### Import ###
# Python modules
from __future__ import absolute_import
from __future__ import print_function
import os, sys
import readline
import time
import Pyro4
from six.moves import input
import json
# TeCS modules
from gtecs.tecs_modules import misc
from gtecs.tecs_modules import params
from gtecs.tecs_modules import flags
from gtecs.tecs_modules import daemons

########################################################################
# Interactive functions

def interactive():
    while True:
        i_in = input('{}> '.format(daemon_ID)).split()
        if len(i_in) > 0:
            command, *args = i_in
            if command == 'q' or command == 'exit':
                return
            else:
                with misc.print_errors():
                    query(command, args)

def query(command, args):
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Primary control functions
    if command == 'start':
        c = daemons.start_daemon(daemon_ID)
        if c: print(c)

    elif command == 'shutdown':
        c = daemons.shutdown_daemon(daemon_ID)
        if c: print(c)

    elif command == 'restart':
        c = daemons.restart_daemon(daemon_ID)
        if c: print(c)

    elif command == 'kill':
        c = daemons.kill_daemon(daemon_ID)
        if c: print(c)

    elif command == 'ping':
        c = daemons.ping_daemon(daemon_ID)
        if c: print(c)

    elif command == 'help' or command == '?':
        print_instructions()

    elif command == 'i':
        raise misc.InputError('Already in interactive mode')

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Daemon functions
    elif command == 'info':
        if len(args) == 0:
            info = daemons.daemon_function(daemon_ID, 'get_info')
            if info: print_info_s(info)
        elif len(args) == 1 and args[0] in ['v','V','-v','-V']:
            info = daemons.daemon_function(daemon_ID, 'get_info')
            if info: print_info(info)
        else:
            raise misc.InputError('Invalid arguments')

    elif command == 'open':
        if len(args) == 0:
            side = 'both'
            fraction = 1
        elif len(args) == 1 and not misc.is_num(args[0]):
            side = args[0]
            fraction = 1
        elif len(args) == 1 and misc.is_num(args[0]):
            side = 'both'
            fraction = float(args[0])
        elif len(args) == 2 and misc.is_num(args[1]):
            side = args[0]
            fraction = float(args[1])
        else:
            raise misc.InputError('Invalid arguments')
        if 0 < fraction <= 1:
            c = daemons.daemon_function(daemon_ID, 'open_dome', [side, fraction])
            if c: print(c)
        else:
            raise misc.InputError('Fraction must be between 0 and 1')

    elif command == 'close':
        if len(args) == 0:
            side  = 'both'
            fraction = 1
        elif len(args) == 1 and not misc.is_num(args[0]):
            side = args[0]
            fraction = 1
        elif len(args) == 1 and misc.is_num(args[0]):
            side = 'both'
            fraction = float(args[0])
        elif len(args) == 2 and misc.is_num(args[1]):
            side = args[0]
            fraction = float(args[1])
        else:
            raise misc.InputError('Invalid arguments')
        if 0 < fraction <= 1:
            c = daemons.daemon_function(daemon_ID, 'close_dome', [side, fraction])
            if c: print(c)
        else:
            raise misc.InputError('Fraction must be between 0 and 1')

    elif command in ['halt','stop','abort']:
        c = daemons.daemon_function(daemon_ID, 'halt_dome')
        if c: print(c)

    elif command == 'weather':
        if args[0] == 'on':
            override = False
        elif args[0] == 'off':
            override = True
        else:
            raise misc.InputError('Invalid arguments')
        with open(params.CONFIG_PATH + 'overrides_flags') as f:
            data = json.load(f)
            if override:
                data['dome_auto'] = 0
                print('Dome in auto mode: will close in bad weather')
            else:
                data['dome_auto'] = 1
                print('Auto weather override set: Dome will NOT close in bad weather')
            json.dump(data, f)

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Unrecognized function
    else:
        raise misc.InputError('Unrecognized command "%s"' %command)

########################################################################
# Output formatting functions

def print_info(info):
    print('######## DOME INFO ########')
    print('North:       %s' %info['north'].capitalize())
    print('South:       %s' %info['south'].capitalize())
    print('Hatch:       %s' %info['hatch'].capitalize())
    print('~~~~~~~')
    print('Uptime: %.1fs' %info['uptime'])
    print('Ping: %.5fs' %info['ping'])
    print('Timestamp: %s' %info['timestamp'])
    print('###########################')

def print_info_s(info):
    if (('open' in info['north']) or ('open' in info['south']) or
        ('ing'  in info['north']) or ('ing' in info['south'])):
        print('DOME:    [Open]')
    else:
        print('DOME:    [%s]' %info['north'].capitalize())
    print('HATCH:   [%s]' %info['hatch'].capitalize())

def print_instructions():
    help_str = misc.bold('Usage:') + ' dome [command]' + '\n' +\
    ' ' + misc.undl('Daemon commands') + ':' + '\n' +\
    '  dome ' + misc.bold('start') + '                       - start the daemon' + '\n' +\
    '  dome ' + misc.bold('shutdown') + '                    - shutdown the daemon' + '\n' +\
    '  dome ' + misc.bold('restart') + '                     - restart the daemon' + '\n' +\
    '  dome ' + misc.bold('kill') + '                        - kill the daemon (' + misc.rtxt('emergency use') + ')' + '\n' +\
    '  dome ' + misc.bold('ping') + '                        - ping the daemon' + '\n' +\
    ' ' + misc.undl('Dome commands') + ':' + '\n' +\
    '  dome ' + misc.bold('open') + ' [north|south]        ' + '  - open the dome' + '\n' +\
    '  dome ' + misc.bold('close') + ' [north|south]        ' + ' - close the dome' + '\n' +\
    '  dome ' + misc.bold('halt') + '/' + misc.bold('stop')+ '                   - stop the dome moving' + '\n' +\
    '  dome ' + misc.bold('weather') + ' [on|off]            - set weather override' + '\n' +\
    '  dome ' + misc.bold('info') + ' [v]' + '                    - report current status' + '\n' +\
    ' ' + misc.undl('Control commands') + ':' + '\n' +\
    '  dome ' + misc.bold('i') + '                           - enter interactive mode' + '\n' +\
    '  dome ' + misc.bold('q') + '/' + misc.bold('exit') + '                      - quit interactive mode' + '\n' +\
    '  dome ' + misc.bold('?') + '/' + misc.bold('help') + '                      - print these instructions'
    print(help_str)

########################################################################

daemon_ID = os.path.basename(__file__)

if len(sys.argv) == 1:
    print_instructions()
else:
    command, *args = sys.argv[1:]
    if command == 'i':
        interactive()
    else:
        with misc.print_errors():
            query(command, args)
