#!/usr/bin/env python

########################################################################
#                                foc.py                                #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#           G-TeCS script to provide control over foc_daemon           #
#                    Martin Dyer, Sheffield, 2015-16                   #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

### Import ###
# Python modules
from __future__ import absolute_import
from __future__ import print_function
import os, sys
import readline
import time
import Pyro4
from six.moves import input
# TeCS modules
from gtecs.tecs_modules import misc
from gtecs.tecs_modules import params

########################################################################
# Interactive functions

def interactive():
    while True:
        i_in = input('{}> '.format(daemon_ID)).split()
        if len(i_in) > 0:
            command, *args = i_in
            if command == 'q' or command == 'exit':
                return
            else:
                query(command, args)

def query(command, args):
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Primary control functions
    if command == 'start':
        misc.start_daemon(daemon_ID)
    elif command == 'shutdown':
        misc.shutdown_daemon(daemon_ID)
    elif command == 'kill':
        misc.kill_daemon(daemon_ID)
    elif command == 'ping':
        misc.ping_daemon(daemon_ID)
    elif command == 'help' or command == '?':
        print_instructions()
    elif command == 'i':
        print(misc.ERROR('Already in interactive mode'))

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Focuser control functions
    elif command == 'info':
        if len(args) == 0:
            info = misc.daemon_function(daemon_ID, 'get_info')
            if info: print_info_s(info)
        elif len(args) == 1 and args[0] in ['v','V','-v','-V']:
            info = misc.daemon_function(daemon_ID, 'get_info')
            if info: print_info(info)
        else:
            print(misc.ERROR('Invalid arguments'))

    elif command == 'set':
        if len(args) == 1 and misc.is_num(args[0]):
            pos     = int(args[0])
            HW_list = list(params.TEL_DICT)
            c = misc.daemon_function(daemon_ID, 'set_focuser', [pos, HW_list])
            if c: print(c)
        elif len(args) == 2 and misc.is_num(args[1]):
            pos     = int(args[1])
            HW_list = misc.valid_ints(args[0].split(','),list(params.TEL_DICT))
            if len(HW_list) > 0:
                c = misc.daemon_function(daemon_ID, 'set_focuser', [pos, HW_list])
                if c: print(c)
        else:
            print(misc.ERROR('Invalid arguments'))

    elif command == 'move':
        if len(args) == 1 and misc.is_num(args[0]):
            steps   = int(args[0])
            HW_list = list(params.TEL_DICT)
            c = misc.daemon_function(daemon_ID, 'move_focuser', [steps, HW_list])
            if c: print(c)
        elif len(args) == 2 and misc.is_num(args[1]):
            steps   = int(args[1])
            HW_list = misc.valid_ints(args[0].split(','),list(params.TEL_DICT))
            if len(HW_list) > 0:
                c = misc.daemon_function(daemon_ID, 'move_focuser', [steps, HW_list])
                if c: print(c)
        else:
            print(misc.ERROR('Invalid arguments'))

    elif command == 'home':
        if len(args) == 0:
            HW_list = list(params.TEL_DICT)
            c = misc.daemon_function(daemon_ID, 'home_focuser', [HW_list])
            if c: print(c)
        elif len(args) == 1:
            HW_list = misc.valid_ints(args[0].split(','),list(params.TEL_DICT))
            if len(HW_list) > 0:
                c = misc.daemon_function(daemon_ID, 'home_focuser', [HW_list])
                if c: print(c)
        else:
            print(misc.ERROR('Invalid arguments'))

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Unrecognized function
    else:
        print(misc.ERROR('Unrecognized command "%s"' %command))

########################################################################
# Output formatting functions

def print_info(info):
    print('###### FOCUSER INFO #######')
    for tel in params.TEL_DICT:
        print('FOCUSER ' + str(tel) + ' (%s-%i)'%tuple(params.TEL_DICT[tel]))
        if info['status'+str(tel)] != 'Moving':
            print('Status: %s' %info['status'+str(tel)])
        else:
            print('Status: %s (%i)' %(info['status'+str(tel)],info['remaining'+str(tel)]))
        print('Current motor pos:    %s' %info['current_pos'+str(tel)])
        print('Maximum motor limit:  %s' %info['limit'+str(tel)])
        print('Internal temperature: %s' %info['int_temp'+str(tel)])
        print('External temperature: %s' %info['ext_temp'+str(tel)])
        print('Serial number:        %s' %info['serial_number'+str(tel)])
        print('~~~~~~~')
    print('Uptime: %.1fs' %info['uptime'])
    print('Ping: %.5fs' %info['ping'])
    print('Timestamp: %s' %info['timestamp'])
    print('###########################')

def print_info_s(info):
    for tel in params.TEL_DICT:
        print('FOCUSER ' + str(tel) + ' (%s-%i)'%tuple(params.TEL_DICT[tel]), end=' ')
        if info['status'+str(tel)] != 'Moving':
            print('  Current position: %s/%s' %(info['current_pos'+str(tel)],info['limit'+str(tel)]), end=' ')
            print('  [%s]' %info['status'+str(tel)])
        else:
            print('  %s (%i)' %(info['status'+str(tel)],info['remaining'+str(tel)]))

def print_instructions():
    help_str = misc.bold('Usage:') + ' foc [command]' + '\n' +\
    ' ' + misc.undl('Daemon commands') + ':' + '\n' +\
    '  foc ' + misc.bold('start') + '             - start the daemon' + '\n' +\
    '  foc ' + misc.bold('shutdown') + '          - shutdown the daemon' + '\n' +\
    '  foc ' + misc.bold('kill') + '              - kill the daemon (' + misc.rtxt('emergency use') + ')' + '\n' +\
    '  foc ' + misc.bold('ping') + '              - ping the daemon' + '\n' +\
    ' ' + misc.undl('Focuser commands') + ':' + '\n' +\
    '  foc ' + misc.bold('move') + ' [tels] steps' + ' - move by the given steps' + '\n' +\
    '  foc ' + misc.bold('set') + ' [tels] pos' + '    - move to the given position' + '\n' +\
    '  foc ' + misc.bold('home') + ' [tels]' + '       - move to the home position' + '\n' +\
    '  foc ' + misc.bold('info') + ' [v]' + '          - report current status' + '\n' +\
    ' ' + misc.undl('Control commands') + ':' + '\n' +\
    '  foc ' + misc.bold('i') + '                 - enter interactive mode' + '\n' +\
    '  foc ' + misc.bold('q') + '/' + misc.bold('exit') + '            - quit interactive mode' + '\n' +\
    '  foc ' + misc.bold('?') + '/' + misc.bold('help') + '            - print these instructions'
    print(help_str)

########################################################################

daemon_ID = os.path.basename(__file__)

if len(sys.argv) == 1:
    print_instructions()
else:
    command, *args = sys.argv[1:]
    if command == 'i':
        interactive()
    else:
        query(command, args)
