#!/usr/bin/env python
"""
A script to provide regularly updated status information from the daemons
"""

import os
import sys
import time
import datetime
import subprocess

from gtecs import misc
from gtecs import params


if __name__ == '__main__':
    if len(sys.argv) > 1:
        daemons = sys.argv[1:]
    else:
        daemons = list(params.DAEMONS)
    while True:
        s = ''
        for d in daemons:
            s += misc.python_command(d+'.py', 'info') + '\n'
        now = datetime.datetime.utcnow()
        print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        print(now.strftime('%Y-%m-%d %H:%M:%S') + '\n')
        print(s)
        time.sleep(0.5)
