#!/usr/bin/env python

########################################################################
#                              follower.py                             #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#     G-TeCS script to provide regularly updated status infomation     #
#                     Martin Dyer, Sheffield, 2015                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

### Import ###
# Python modules
from __future__ import absolute_import
from __future__ import print_function
import os, sys
import time, datetime
import subprocess
# TeCS modules
from gtecs.tecs_modules import misc
from gtecs.tecs_modules import params

if __name__ == '__main__':
    if len(sys.argv) > 1:
        daemons = sys.argv[1:]
    else:
        daemons = list(params.DAEMONS)
    while True:
        s = ''
        for d in daemons:
            s += misc.python_command(d+'.py', 'info') + '\n'
        now = datetime.datetime.utcnow()
        print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        print(now.strftime('%Y-%m-%d %H:%M:%S') + '\n')
        print(s)
        time.sleep(0.5)
