#!/usr/bin/env python3
"""A script to provide control over the UT interface daemons."""

import json
import os
import sys

from gtecs.common import logging
from gtecs.common.style import errortxt
from gtecs.common.system import execute_long_command
from gtecs.control import daemons
from gtecs.control import misc
from gtecs.control import params


def query(command, args):
    """Process a query."""
    # Primary daemon control
    if command == 'start':
        if len(args) == 0:
            uts = params.UTS
            hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 1:
            if args[0] in ['cam', 'foc', 'filt']:
                uts = params.UTS
                hw_list = misc.valid_strings(args[0].split(','), ['cam', 'foc', 'filt'])
            else:
                uts = misc.valid_ints(args[0].split(','), params.UTS)
                hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 2:
            uts = misc.valid_ints(args[0].split(','), params.UTS)
            hw_list = misc.valid_strings(args[1].split(','), ['cam', 'foc', 'filt'])
        else:
            raise ValueError('Invalid arguments')
        for ut in uts:
            for hw in hw_list:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    host, port = daemons.get_daemon_host(interface_id)
                    pid = daemons.start_daemon(interface_id)
                    print(f'Daemon {interface_id} started on {host}:{port} (PID {pid})')
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))

    elif command == 'shutdown':
        if len(args) == 0:
            uts = params.UTS
            hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 1:
            if args[0] in ['cam', 'foc', 'filt']:
                uts = params.UTS
                hw_list = misc.valid_strings(args[0].split(','), ['cam', 'foc', 'filt'])
            else:
                uts = misc.valid_ints(args[0].split(','), params.UTS)
                hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 2:
            uts = misc.valid_ints(args[0].split(','), params.UTS)
            hw_list = misc.valid_strings(args[1].split(','), ['cam', 'foc', 'filt'])
        else:
            raise ValueError('Invalid arguments')
        for ut in uts:
            for hw in hw_list:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    host, port = daemons.get_daemon_host(interface_id)
                    daemons.shutdown_daemon(interface_id)
                    print(f'Daemon {interface_id} shutdown on {host}:{port}')
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))

    elif command == 'restart':
        if len(args) == 0:
            uts = params.UTS
            hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 1:
            if args[0] in ['cam', 'foc', 'filt']:
                uts = params.UTS
                hw_list = misc.valid_strings(args[0].split(','), ['cam', 'foc', 'filt'])
            else:
                uts = misc.valid_ints(args[0].split(','), params.UTS)
                hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 2:
            uts = misc.valid_ints(args[0].split(','), params.UTS)
            hw_list = misc.valid_strings(args[1].split(','), ['cam', 'foc', 'filt'])
        else:
            raise ValueError('Invalid arguments')
        for ut in uts:
            for hw in hw_list:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    host, port = daemons.get_daemon_host(interface_id)
                    pid = daemons.restart_daemon(interface_id)
                    print(f'Daemon {interface_id} restarted on {host}:{port} (PID {pid})')
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))

    elif command == 'kill':
        if len(args) == 0:
            uts = params.UTS
            hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 1:
            if args[0] in ['cam', 'foc', 'filt']:
                uts = params.UTS
                hw_list = misc.valid_strings(args[0].split(','), ['cam', 'foc', 'filt'])
            else:
                uts = misc.valid_ints(args[0].split(','), params.UTS)
                hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 2:
            uts = misc.valid_ints(args[0].split(','), params.UTS)
            hw_list = misc.valid_strings(args[1].split(','), ['cam', 'foc', 'filt'])
        else:
            raise ValueError('Invalid arguments')
        for ut in uts:
            for hw in hw_list:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    host, port = daemons.get_daemon_host(interface_id)
                    daemons.shutdown_daemon(interface_id, kill=True)
                    print(f'Daemon {interface_id} killed on {host}:{port}')
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))

    elif command in ['check', 'ping']:
        if len(args) == 0:
            uts = params.UTS
            hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 1:
            if args[0] in ['cam', 'foc', 'filt']:
                uts = params.UTS
                hw_list = misc.valid_strings(args[0].split(','), ['cam', 'foc', 'filt'])
            else:
                uts = misc.valid_ints(args[0].split(','), params.UTS)
                hw_list = ['cam', 'foc', 'filt']
        elif len(args) == 2:
            uts = misc.valid_ints(args[0].split(','), params.UTS)
            hw_list = misc.valid_strings(args[1].split(','), ['cam', 'foc', 'filt'])
        else:
            raise ValueError('Invalid arguments')
        for ut in uts:
            for hw in hw_list:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    host, port = daemons.get_daemon_host(interface_id)
                    pid = daemons.check_daemon(interface_id)
                    print(f'Daemon {interface_id} is running on {host}:{port} (PID {pid})')
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))

    elif command in ['info', 'status']:
        if len(args) == 0:
            info_type = 'verbose'
            force = False
        elif len(args) == 1 and args[0] in ['f', 'F', '-f', '-F', '--force-update']:
            info_type = 'verbose'
            force = True
        elif len(args) == 1 and args[0] in ['r', 'R', '-r', '-R', '--raw']:
            info_type = 'raw'
            force = False
        elif (len(args) == 2 and
              ((args[0] in ['r', 'R', '-r', '-R', '--raw'] and
                args[1] in ['f', 'F', '-f', '-F', '--force-update']) or
               (args[1] in ['r', 'R', '-r', '-R', '--raw'] and
                args[0] in ['f', 'F', '-f', '-F', '--force-update']))):
            info_type = 'raw'
            force = True
        else:
            raise ValueError('Invalid arguments')
        all_info = {}
        for ut in params.UTS:
            ut_info = []
            for hw in ['cam', 'foc', 'filt']:
                interface_id = f'{hw}{ut}'
                if interface_id not in params.INTERFACES:
                    continue
                try:
                    daemons.check_daemon(interface_id)
                    with daemons.daemon_proxy(interface_id) as daemon:
                        info = daemon.get_info(force)
                    if not info:
                        raise ValueError('No info returned, check daemon')
                    ut_info.append(info)
                except Exception as error:
                    print(errortxt('"{}: {}"'.format(type(error).__name__, error)))
            all_info[ut] = ut_info
        if info_type == 'verbose':
            for ut in all_info:
                if len(all_info[ut]) > 0:
                    print(f"UT {ut} ({params.UT_DICT[ut]['INTERFACE_HOST']}):")
                for info in all_info[ut]:
                    host, port = daemons.get_daemon_host(info['daemon_id'])
                    print('  {:>5} ({}:{}): {}'.format(
                        info['daemon_id'], host, port, info['serial']))
        elif info_type == 'raw':
            for ut in params.UTS:
                for info in all_info[ut]:
                    print(json.dumps(info, indent=2, default=repr))

    elif command in ['log', 'tail']:
        if 'stdout' in args:
            stdout = True
            args.remove('stdout')
        else:
            stdout = False
        if args[0] in ['cam', 'foc', 'filt']:
            hw_list = [args[0]]
            args.remove(args[0])

        for i, ut in enumerate(params.UTS):
            for j, hw in enumerate(hw_list):
                interface_id = f'{hw}{ut}'
                if stdout:
                    log_file = interface_id + '-stdout.log'
                else:
                    log_file = interface_id + '.log'
                log_path = logging.get_log_path() / log_file
                tail_command = 'tail {} {}'.format(log_path, ' '.join(args))
                if i + j > 0:
                    print('~~~~~~~~~~~~~~~~~~~~~~')
                execute_long_command(tail_command)

    # Unrecognized function
    else:
        raise ValueError('Unrecognized command "{}"'.format(command))


if __name__ == '__main__':
    daemon_id = os.path.basename(__file__)

    try:
        command, *args = sys.argv[1:]
    except ValueError:
        # no command, print help and exit
        command = 'help'

    if command in ['help', '?']:
        print(
            'Usage: intf command [options]',
            'Daemon commands:',
            '  start [uts] [cam|foc|filt]         start the interfaces',
            '  shutdown [uts] [cam|foc|filt]      shutdown the interfaces',
            '  restart  [uts] [cam|foc|filt]      restart the interfaces',
            '  kill [uts] [cam|foc|filt]          kill the interfaces',
            '  check/ping [uts] [cam|foc|filt]    check the interfaces for errors',
            'Interface commands:',
            '  info/status [-r] [-f]              report current status [raw/force-update]',
            '  log [stdout] [cam|foc|filt]        print daemon log (tail alias)',
            'Control commands:',
            '  i                                  enter interactive mode',
            '  q/exit                             quit interactive mode',
            '  ?/help                             print these instructions',
            sep='\n')
        sys.exit()

    if command == 'i':
        while True:
            try:
                interactive_input = input(f'{os.path.basename(__file__)}> ').split()
            except EOFError:
                print()
                sys.exit()
            if len(interactive_input) > 0:
                command, *args = interactive_input
                if command in ['q', 'exit']:
                    sys.exit()
                if command == 'i':
                    print(errortxt('"ValueError: Already in interactive mode"'))
                    continue
                try:
                    query(command, args)
                except Exception as error:
                    print(errortxt(f'"{type(error).__name__}: {error}"'))

    try:
        query(command, args)
    except Exception as error:
        print(errortxt(f'"{type(error).__name__}: {error}"'))
