#!/usr/bin/env python
"""A script to provide control over the UT interface daemons."""

import os
import sys

from gtecs import daemons
from gtecs import errors
from gtecs import misc
from gtecs import params


DAEMON_ID = os.path.basename(__file__)

DAEMON_IDS = []
for daemon_id in params.DAEMONS:
    if daemon_id in params.UT_INTERFACES:
        DAEMON_IDS.append(daemon_id)
DAEMON_IDS.sort()


def query(command, args, daemon_ids):
    """Process a query."""
    # Command functions
    if command in ['help', '?']:
        print_instructions()

    elif command == 'i':
        raise errors.InputError('Already in interactive mode')

    # Primary daemon control
    elif command == 'start':
        for daemon_id in daemon_ids:
            with misc.print_errors():
                reply = daemons.start_daemon(daemon_id)
                print(reply)

    elif command == 'shutdown':
        for daemon_id in daemon_ids:
            with misc.print_errors():
                reply = daemons.shutdown_daemon(daemon_id)
                print(reply)

    elif command == 'restart':
        for daemon_id in daemon_ids:
            with misc.print_errors():
                reply = daemons.restart_daemon(daemon_id)
                print(reply)

    elif command == 'kill':
        for daemon_id in daemon_ids:
            with misc.print_errors():
                reply = daemons.kill_daemon(daemon_id)
                print(reply)

    elif command in ['check', 'ping']:
        for daemon_id in daemon_ids:
            with misc.print_errors():
                reply = daemons.check_daemon(daemon_id)
                print(reply)

    elif command in ['info', 'status']:
        for daemon_id in daemon_ids:
            with misc.print_errors():
                # send command
                reply = daemons.daemon_function(daemon_id, 'get_info', args=[False])
                # print response
                if not reply:
                    raise ValueError('No info returned, check daemon')
                else:
                    print_info(reply)

    elif command in ['log', 'tail']:
        if 'stdout' in args:
            stdout = True
            args.remove('stdout')
        else:
            stdout = False
        for daemon_id in daemon_ids:
            # parse arguments
            if stdout:
                log_file = daemon_id + '-stdout.log'
            else:
                log_file = daemon_id + '.log'
            log_path = os.path.join(params.LOG_PATH, log_file)
            tail_command = 'tail {} {}'.format(log_path, ' '.join(args))
            # send command
            misc.execute_long_command(tail_command)

    # Unrecognized function
    else:
        raise errors.InputError('Unrecognized command "{}"'.format(command))


def print_info(info):
    """Print the full info dict."""
    print('INTERFACE {}:'.format(info['daemon_id']))
    print('   Cameras:       ', end='\t')
    for ut in info['cam_serials']:
        print('{}: {: <14}'.format(ut, info['cam_serials'][ut]), end='  ')
    print('')
    print('   Focusers:      ', end='\t')
    for ut in info['foc_serials']:
        print('{}: {: <14}'.format(ut, info['foc_serials'][ut]), end='  ')
    print('')
    print('   Filter Wheels: ', end='\t')
    for ut in info['filt_serials']:
        print('{}: {: <14}'.format(ut, info['filt_serials'][ut]), end='  ')
    print('')


def print_instructions():
    """Print instructions for using the daemon."""
    print('Usage: intf command [options]',
          'Daemon commands:',
          '  start                          start the interfaces',
          '  shutdown                       shutdown the interfaces',
          '  restart                        restart the interfaces',
          '  kill                           kill the interfaces',
          '  check/ping                     check the interfaces for errors',
          'Interface commands:',
          '  info/status [v]                report current status',
          '  log [stdout]                   print daemon log (tail alias)',
          'Control commands:',
          '  i                              enter interactive mode',
          '  q/exit                         quit interactive mode',
          '  ?/help                         print these instructions',
          sep='\n')


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print_instructions()
    else:
        command, *args = sys.argv[1:]
        if command == 'i':
            while True:
                interactive_input = input('{}> '.format(DAEMON_ID)).split()
                if len(interactive_input) > 0:
                    command, *args = interactive_input
                    if command in ['q', 'exit']:
                        break
                    else:
                        with misc.print_errors():
                            query(command, args, DAEMON_IDS)
        else:
            with misc.print_errors():
                query(command, args, DAEMON_IDS)
