#!/usr/bin/env python3
"""A script to provide overall control of the daemons."""

import sys
import time

from gtecs.control import daemons
from gtecs.control import misc
from gtecs.control import params


if __name__ == '__main__':
    command = sys.argv[1]
    all_daemons = list(params.DAEMONS) + list(params.INTERFACES)
    if len(sys.argv) == 3:
        daemon_ids = sorted(misc.valid_strings(sys.argv[2].split(','), all_daemons))
    elif len(sys.argv) > 3:
        daemon_ids = sorted(sys.argv[2:])
    else:
        daemon_ids = sorted(all_daemons)

    if command == 'start':
        for daemon_id in daemon_ids:
            try:
                host, port = daemons.get_daemon_host(daemon_id)
                pid = daemons.start_daemon(daemon_id)
                print(f'Daemon {daemon_id} started on {host}:{port} (PID {pid})')
            except Exception as error:
                print(error)

    elif command == 'shutdown':
        for daemon_id in daemon_ids:
            try:
                host, port = daemons.get_daemon_host(daemon_id)
                daemons.shutdown_daemon(daemon_id)
                print(f'Daemon {daemon_id} shutdown on {host}:{port}')
            except Exception as error:
                print(error)

    elif command == 'restart':
        for daemon_id in daemon_ids:
            try:
                host, port = daemons.get_daemon_host(daemon_id)
                pid = daemons.restart_daemon(daemon_id)
                print(f'Daemon {daemon_id} restarted on {host}:{port} (PID {pid})')
            except Exception as error:
                print(error)

    elif command == 'kill':
        for daemon_id in daemon_ids:
            try:
                host, port = daemons.get_daemon_host(daemon_id)
                daemons.shutdown_daemon(daemon_id, kill=True)
                print(f'Daemon {daemon_id} killed on {host}:{port}')
            except Exception as error:
                print(error)

    elif command == 'ping':
        for daemon_id in daemon_ids:
            try:
                host, port = daemons.get_daemon_host(daemon_id)
                pid = daemons.check_daemon(daemon_id)
                print(f'Daemon {daemon_id} is running on {host}:{port} (PID {pid})')
            except Exception as error:
                print(error)

    else:
        print(f'"{command}" not in valid commands (start, shutdown, restart, kill, ping)')
