#!/usr/bin/env python
"""
A script to provide overall control of the daemons
"""

import os
import sys
import time
import readline
import Pyro4

from gtecs.misc import execute_command
from gtecs import params


if __name__ == '__main__':
    if sys.argv[1] in ['start', 'shutdown', 'kill', 'ping']:
        if len(sys.argv) > 2:
            daemons = sys.argv[2:]
        else:
            daemons = list(params.DAEMONS)

        # remove individual fli interfaces and replace with one command
        if any([intf in daemons for intf in params.FLI_INTERFACES]):
            for intf in params.FLI_INTERFACES:
                if intf in daemons:
                    daemons.remove(intf)
            daemons.append('fli')

        # handle dependencies
        if 'exq' in daemons:
            # exq needs to start after cam and filt and shutdown first
            if sys.argv[1] == 'start':
                daemons.remove('exq')
                daemons.append('exq')
            elif sys.argv[1] == 'shutdown':
                # move to front
                daemons.remove('exq')
                daemons.insert(0, 'exq')
        if 'fli' in daemons:
            # interfaces need to start before the daemons and shutdown after
            if sys.argv[1] == 'start':
                # move to front
                daemons.remove('fli')
                daemons.insert(0, 'fli')
            elif sys.argv[1] == 'shutdown':
                # move to back
                daemons.remove('fli')
                daemons.append('fli')

        for d in daemons:
            command = '{} {}'.format(d, sys.argv[1])
            execute_command(command)
            time.sleep(1)
    else:
        print('Valid commands: start, shutdown, kill, ping')
