#!/usr/bin/env python
"""
A simple script to change into manual mode
"""

from gtecs import flags
from gtecs import params

status = flags.Status()

# set observer
username = input('Please enter your name for the record: ')
if len(username) == 0:
    username = 'Unknown'
with open(params.CONFIG_PATH + 'observer', 'w') as f:
    f.write(username)
print('Thank you "{}", everything will now be blamed on you'.format(username))

# set mode to manual
status.mode = 'manual'

print('System now in Manual mode, you are in control')
