#!/usr/bin/env python

import sys
import json

from gtecs.tecs_modules import params
from gtecs.tecs_modules import misc

CURRENT_OBSERVER = misc.get_observer()

with open(params.CONFIG_PATH + 'overrides_flags', 'r') as f:
    overrides = json.load(f)

if overrides['robotic'] == 0:
    # The 'robotic' overide flag is False. Therefore we're in robotic mode.
    CURRENT_MODE = 'ROBOTIC'
elif overrides['robotic'] == 1:
    # The 'robotic' overide flag is True. Therefore we're in manual mode.
    CURRENT_MODE = 'MANUAL'

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('Usage: mode [manual|robotic]')
        print('  System is currently in {} mode.'.format(CURRENT_MODE))
        print('  Current observer is "{}".'.format(CURRENT_OBSERVER))
    else:
        m_args = ['m', '-m', 'manual', '--manual']
        r_args = ['r', '-r', 'robotic', '--robotic']
        new_mode = sys.argv[1]
        if new_mode.lower() not in r_args+m_args:
            print('ERROR: "{}" is an invalid mode'.format(name))
            print('Usage: mode [manual|robotic]')
        else:
            if new_mode.lower() in m_args:
                misc.execute_command('manual_mode')
            elif new_mode.lower() in r_args:
                misc.execute_command('robotic_mode')
