#!/usr/bin/env python3
"""A script to change the system control mode."""

import sys

from gtecs.common.style import rtxt
from gtecs.control import flags
from gtecs.control.slack import send_slack_msg

status = flags.Status()

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('System is currently in {} mode'.format(status.mode.upper()))
        print('Current observer is "{}"'.format(status.observer))
        if status.emergency_shutdown:
            print(rtxt('EMERGENCY SHUTDOWN IS ACTIVE'))
        print('See "mode --help" for usage')
        sys.exit()

    command = sys.argv[1].lower()

    # ROBOTIC mode
    # this sets the observer to "GOTO-pilot"
    if command in ['r', '-r', 'robotic', '--robotic']:
        status.mode = 'robotic'
        print('System now in Robotic mode')
        print('The pilot is in control')
        sys.exit()

    # MANUAL mode
    # this asks for observer name
    if command in ['m', '-m', 'manual', '--manual']:
        username = input('Please enter your name for the record: ')
        if len(username) == 0:
            username = 'Unknown'
        status.observer = username
        print('Thank you "{}", everything will now be blamed on you'.format(username))

        status.mode = 'manual'
        print('System now in Manual mode')
        print('All automated systems are on, but can be disabled at your own risk')
        sys.exit()

    # ENGINEERING mode
    # this also asks for observer name
    if command in ['e', '-e', 'engineering', '--engineering']:
        print('ATTENTION: Engineering mode should *only* be used when there are workers on-site')
        print('           To disable the telescope remotely you can switch to manual mode and ')
        print('           enable the conditions override to prevent the dome opening')

        username = input('Please enter your name for the record: ')
        if len(username) == 0:
            username = 'Unknown'
        status.observer = username
        print('Thank you "{}", everything will now be blamed on you'.format(username))

        status.mode = 'engineering'
        print('System now in Engineering mode')
        print('WARNING: All automated systems are now disabled, inclusing autoclose in bad weather')
        sys.exit()

    # Create EMERGENCY-SHUTDOWN file
    if command == 'lockdown':
        reason = input('Please enter reason for the lockdown: ')
        if len(reason) == 0:
            reason = 'unknown'

        status.create_shutdown_file(reasons=[reason])
        send_slack_msg('Emergency shutdown: {}'.format(reason))
        print('Lockdown file created at {}'.format(status.emergency_file))
        print('The dome will not open until that file is deleted')
        sys.exit()

    if command not in ['h', '-h', 'help', '--help']:
        print('ERROR: "{}" is an invalid mode'.format(command.strip('-')))

    print('Usage: mode [option]')
    print('Valid modes:')
    print('  -r, --robotic        Robotic pilot control')
    print('  -m, --manual         Remote or on-site human control')
    print('  -e, --engineering    All automatic systems disabled')
    print('Other valid commands:')
    print('  lockdown             Create the EMERGENCY-SHUTDOWN file to prevent the dome opening')
