#!/usr/bin/env python
"""A script to change the system control mode."""

import sys

from gtecs import flags

status = flags.Status()

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('System is currently in {} mode'.format(status.mode.upper()))
        print('Current observer is "{}"'.format(status.observer))
        print('See "mode --help" for usage')
        sys.exit()

    command = sys.argv[1].lower()

    # ROBOTIC mode
    # this sets the observer to "GOTO-pilot"
    if command in ['r', '-r', 'robotic', '--robotic']:
        status.mode = 'robotic'
        print('System now in Robotic mode')
        print('The pilot is in control')
        sys.exit()

    # MANUAL mode
    # this asks for observer name
    if command in ['m', '-m', 'manual', '--manual']:
        username = input('Please enter your name for the record: ')
        if len(username) == 0:
            username = 'Unknown'
        status.observer = username
        print('Thank you "{}", everything will now be blamed on you'.format(username))

        status.mode = 'manual'
        print('System now in Manual mode')
        print('You are in control')
        sys.exit()

    # ENGINEERING mode
    # this also asks for observer name
    if command in ['e', '-e', 'engineering', '--engineering']:
        username = input('Please enter your name for the record: ')
        if len(username) == 0:
            username = 'Unknown'
        status.observer = username
        print('Thank you "{}", everything will now be blamed on you'.format(username))

        status.mode = 'engineering'
        print('System now in Engineering mode')
        print('All automated systems are disabled')
        sys.exit()

    if command not in ['h', '-h', 'help', '--help']:
        print('ERROR: "{}" is an invalid mode'.format(command.strip('-')))

    print('Usage: mode [option]')
    print('Valid modes:')
    print('  -r, --robotic        Robotic pilot control')
    print('  -m, --manual         Remote or on-site human control')
    print('  -e, --engineering    All automatic systems disabled')
