#!/usr/bin/env python
"""
A script to make it easier for users to run observation scripts
"""

import os
import sys
import pkg_resources

from gtecs import misc

SCRIPT_PATH = pkg_resources.resource_filename('gtecs', 'observing_scripts')

SCRIPT_NAMES = [os.path.splitext(f)[0]
                for f in os.listdir(SCRIPT_PATH)
                if not f.startswith('__')]


def query(script, args):
    if script not in sorted(SCRIPT_NAMES):
        print('ERROR: "{}" script not found'.format(script))
        print('Valid observation scripts:')
        for s in sorted(SCRIPT_NAMES):
                print('\t', s)
    else:
        with misc.make_pid_file('obs_script'):
            command =  ' '.join((sys.executable, SCRIPT_PATH+'/'+script+'.py', *args))
            misc.execute_long_command(command)


def print_instructions():
    script_docs = {}
    for s in SCRIPT_NAMES:
        with open(os.path.join(SCRIPT_PATH,s+'.py')) as f:
            lines = f.readlines()
            script_docs[s] = (lines[1].strip(), lines[2].strip())

    print('Usage: obs_script <script name> [args]')
    print('Valid observation scripts:')
    for s in sorted(SCRIPT_NAMES):
        print('  - {: <26} '.format(script_docs[s][0]), script_docs[s][1])


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print_instructions()
    else:
        script, *args = sys.argv[1:]
        with misc.print_errors():
            query(script, args)
