#!/usr/bin/env python
"""A script to re-install G-TeCS."""

import os
import sys


if len(sys.argv) > 1:
    repo = sys.argv[1]
else:
    repo = '~/g-tecs'

repo = os.path.expanduser(repo)

if not os.path.exists(repo):
    print('ERROR: Repository "{}" does not exist'.format(repo))
    sys.exit()

os.system('pip3 install {} --user --no-deps --upgrade'.format(repo))
