#!/usr/bin/env python

########################################################################
#                            reinstall_gtecs                           #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                  G-TeCS script to re-install G-TeCS                  #
#                      Martin Dyer, Sheffield, 2017                    #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

# Import
import os
import sys

if len(sys.argv) > 1:
    repo = sys.argv[1]
else:
    repo = '~/g-tecs'

repo = os.path.expanduser(repo)

if not os.path.exists(repo):
    print('ERROR: Repository "{}" does not exist'.format(repo))
    sys.exit()

os.system('pip3 install {} --user --no-deps --upgrade'.format(repo))
