#!/usr/bin/env python

import json

from gtecs.tecs_modules import params

with open(params.CONFIG_PATH + 'observer', 'w') as f:
    f.write('GOTO-pilot')

with open(params.CONFIG_PATH + 'overrides_flags', 'r') as f:
    data = json.load(f)
    data['robotic'] = 0 # Set override to False
with open(params.CONFIG_PATH + 'overrides_flags', 'w') as f:
    json.dump(data, f)

print('System now in Robotic mode, the pilot is in control')
