#!/usr/bin/env python
"""
A simple script to change into robotic mode
"""

from gtecs import flags
from gtecs import params

status = flags.Status()

# set observer
with open(params.CONFIG_PATH + 'observer', 'w') as f:
    f.write('GOTO-pilot')

# set mode to manual
status.mode = 'robotic'

print('System now in Robotic mode, the pilot is in control')
