#!/usr/bin/env python
"""
A simple script to change into robotic mode
"""

from gtecs import flags
from gtecs import params

status = flags.Status()

# set mode to robotic
# this will also set the observer to "GOTO-pilot" and turn on dome autoclose
status.mode = 'robotic'
print('System now in Robotic mode, the pilot is in control')
