#!/usr/bin/env python

########################################################################
#                          scheduler_test.py                           #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#             G-TeCS test script for the scheduler system              #
#                     Martin Dyer, Sheffield, 2016                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

from __future__ import absolute_import
from __future__ import print_function

from astropy.time import Time
import astropy.units as u

from gtecs.tecs_modules import scheduler

"""
Test code: goes through a night and returns the current best job.
NOTE jobs are never completed so are never removed from the queue folder.
"""

now = Time('2016-03-08 20:20')
while True:
    now = now + 5*60*u.second
    print(now)
    obs_new = scheduler.check_queue(None, now)
    if obs_new is not None:
        print('   job is', obs_new.id, 'with', obs_new.priority_now)
    else:
        print('   nothing to do, parking')