#!/usr/bin/env python

########################################################################
#                          scheduler_test.py                           #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#             G-TeCS test script for the scheduler system              #
#                     Martin Dyer, Sheffield, 2016                     #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

from __future__ import absolute_import
from __future__ import print_function

import sys

from astropy.time import Time
import astropy.units as u

from gtecs.tecs_modules import scheduler

"""
Test code: goes through a night and returns the current best job.
NOTE jobs are never completed so are never removed from the queue folder.
"""

write_html = 0
if len(sys.argv) > 1:
    write_html = bool(sys.argv[1])

now = Time('2016-08-31 22:00')
while True:
    now = now + 5*60*u.second
    print(now)
    newID, newPriority, newMinTime = scheduler.check_queue(now, write_html)
    if newID is not None:
        print('   job is', newID, 'with', newPriority)
    else:
        print('   nothing to do, parking')
