#!/usr/bin/env python

########################################################################
#                             scheduler.py                             #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
# G-TeCS script to provide control over the scheduler interface daemon #
#                      Martin Dyer, Sheffield, 2017                    #
#           ~~~~~~~~~~~~~~~~~~~~~~~##~~~~~~~~~~~~~~~~~~~~~~~           #
#                   Based on the SLODAR/pt5m system                    #
########################################################################

### Import ###
# Python modules
from __future__ import absolute_import
from __future__ import print_function
import os, sys
import readline
import time
import Pyro4
from six.moves import input
# TeCS modules
from gtecs.tecs_modules import misc
from gtecs.tecs_modules import params
from gtecs.tecs_modules import daemons

########################################################################
# Interactive functions

def interactive():
    while True:
        i_in = input('{}> '.format(daemon_ID)).split()
        if len(i_in) > 0:
            command, *args = i_in
            if command == 'q' or command == 'exit':
                return
            else:
                query(command, args)

def query(command, args):
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Primary control functions
    if command == 'start':
        daemons.start_daemon(daemon_ID)
    elif command == 'shutdown':
        daemons.shutdown_daemon(daemon_ID)
    elif command == 'restart':
        daemons.restart_daemon(daemon_ID)
    elif command == 'kill':
        daemons.kill_daemon(daemon_ID)
    elif command == 'ping':
        daemons.ping_daemon(daemon_ID)
    elif command == 'help' or command == '?':
        print_instructions()
    elif command == 'i':
        print(misc.ERROR('Already in interactive mode'))

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Unrecognized function
    else:
        print(misc.ERROR('Unrecognized command "%s"' %command))

########################################################################
# Output formatting functions

def print_instructions():
    help_str = misc.bold('Usage:') + ' scheduler [command]' + '\n' +\
    ' ' + misc.undl('Interface commands') + ':' + '\n' +\
    '  scheduler ' + misc.bold('start') + '             - start the daemon' + '\n' +\
    '  scheduler ' + misc.bold('shutdown') + '          - shutdown the daemon' + '\n' +\
    '  scheduler ' + misc.bold('restart') + '           - restart the daemon' + '\n' +\
    '  scheduler ' + misc.bold('kill') + '              - kill the daemon (' + misc.rtxt('emergency use') + ')' + '\n' +\
    '  scheduler ' + misc.bold('ping') + '              - ping the daemon' + '\n' +\
    ' ' + misc.undl('Control commands') + ':' + '\n' +\
    '  scheduler ' + misc.bold('i') + '                 - enter interactive mode' + '\n' +\
    '  scheduler ' + misc.bold('q') + '/' + misc.bold('exit') + '            - quit interactive mode' + '\n' +\
    '  scheduler ' + misc.bold('?') + '/' + misc.bold('help') + '            - print these instructions'
    print(help_str)

########################################################################

daemon_ID = os.path.basename(__file__)

if len(sys.argv) == 1:
    print_instructions()
else:
    command, *args = sys.argv[1:]
    if command == 'i':
        interactive()
    else:
        query(command, args)
