#!/usr/bin/env python
"""
A script to setup directory structure for G-TeCS config files
"""

import os
import shutil
import pkg_resources

from gtecs import params


# find package resources
gtecs_data_dir = pkg_resources.resource_filename('gtecs', 'data')
gtecs_html_dir = pkg_resources.resource_filename('gtecs', 'data/html')

# create CONFIG_DIR if necessary and put files there
try:
    if not os.path.exists(params.CONFIG_PATH):
        os.mkdir(params.CONFIG_PATH)

    if not os.path.exists(params.IMAGE_PATH):
        os.mkdir(params.IMAGE_PATH)

    logpath = os.path.join(params.CONFIG_PATH, 'logs')
    if not os.path.exists(logpath):
        os.mkdir(logpath)
    htmlpath = os.path.join(params.CONFIG_PATH, 'html')
    if not os.path.exists(htmlpath):
        os.mkdir(htmlpath)
    queuepath = os.path.join(params.CONFIG_PATH, 'queue')
    if not os.path.exists(queuepath):
        os.mkdir(queuepath)
    for folder in ['todo', 'aborted', 'completed', 'interrupted']:
        folderpath = os.path.join(queuepath, folder)
        if not os.path.exists(folderpath):
            os.mkdir(folderpath)

    # now copy data there
    for data_file in ['conditions_flags', 'overrides_flags',
                      'run_number', 'horizon', 'exposure_queue']:
        shutil.copy(os.path.join(gtecs_data_dir, data_file),
                    os.path.join(params.CONFIG_PATH, data_file))
    for f in os.listdir(gtecs_html_dir):
        shutil.copy(os.path.join(gtecs_html_dir, f),
                    os.path.join(htmlpath, f))
except:
    print('Failed to set up the CONFIG_PATH ', params.CONFIG_PATH,
          'You should create this directory yourself manually')
